name: CI - Build ZAP LSP Server (on Cap'n Proto)

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_gcc:
    name: Build with GCC
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trickstar0301/capnp-prebuilt-ubuntu:1.1.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure CMake with GCC
        run: |
          cmake -B build \
            -DCMAKE_CXX_COMPILER=g++-13 .
      - name: Build Project
        run: cmake --build build

  build_regular:
    name: Regular Build
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trickstar0301/capnp-prebuilt-ubuntu:1.1.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B build .
      - name: Build Project
        run: cmake --build build

  build_release:
    name: Release Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trickstar0301/capnp-prebuilt-ubuntu:1.1.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure CMake with Bundled CapnProto
        run: cmake -B build -DUSE_BUNDLED_CAPNP_TOOL=ON .
      - name: Build Project
        run: cmake --build build
      - name: Rename Binary for Linux x86_64
        run: mv build/zap-ls build/zap-ls-linux-x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-ls-linux-x86_64
          path: build/zap-ls-linux-x86_64

  release:
    name: Create GitHub Release
    needs: [build_release]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Linux x86_64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: zap-ls-linux-x86_64
          path: artifacts

      - name: Grant Execute Permission
        run: chmod +x artifacts/zap-ls-linux-x86_64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/zap-ls-linux-x86_64
          draft: false
          prerelease: false
